"""
sql_validator.py
Guards every SQL statement that reaches the database - whether typed by a
user in the SQL Console or generated by the AI in the Chat tab.

Rule: only a single read-only SELECT (or WITH ... SELECT CTE) statement is
allowed. Anything else is rejected before it ever reaches pyodbc.
"""

import re
from dataclasses import dataclass

FORBIDDEN_KEYWORDS = [
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE",
    "TRUNCATE", "EXEC", "EXECUTE", "MERGE", "GRANT", "REVOKE",
    "DENY", "sp_", "xp_",
]

# Statement must start with SELECT or a CTE (WITH ...) that itself only
# contains SELECTs.
ALLOWED_START_RE = re.compile(r"^\s*(WITH\b|SELECT\b)", re.IGNORECASE)

# Strips line and block comments before keyword scanning, so someone can't
# hide "DROP" inside a comment to fool a naive string search... though we
# don't rely on comment stripping alone, see _contains_forbidden_keyword.
LINE_COMMENT_RE = re.compile(r"--.*?$", re.MULTILINE)
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)

MULTI_STATEMENT_RE = re.compile(r";\s*\S")  # a semicolon followed by more (non-whitespace) content


@dataclass
class ValidationResult:
    is_valid: bool
    reason: str = ""
    cleaned_sql: str = ""


def _strip_comments(sql: str) -> str:
    sql = BLOCK_COMMENT_RE.sub(" ", sql)
    sql = LINE_COMMENT_RE.sub(" ", sql)
    return sql


def _contains_forbidden_keyword(sql: str) -> str | None:
    upper = sql.upper()
    for kw in FORBIDDEN_KEYWORDS:
        pattern = r"\b" + re.escape(kw.upper()) + r"\b" if not kw.endswith("_") else re.escape(kw.upper())
        if re.search(pattern, upper):
            return kw
    return None


def validate_select_only(sql: str) -> ValidationResult:
    if not sql or not sql.strip():
        return ValidationResult(False, "Query is empty.")

    cleaned = _strip_comments(sql).strip()

    # Reject stacked/multiple statements (a trailing semicolon alone is fine).
    trimmed = cleaned.rstrip().rstrip(";").strip()
    if MULTI_STATEMENT_RE.search(cleaned.rstrip()):
        return ValidationResult(False, "Multiple statements are not allowed. Run one SELECT at a time.")

    if not ALLOWED_START_RE.match(trimmed):
        return ValidationResult(False, "Only SELECT statements (optionally via WITH ... CTE) are allowed.")

    bad_kw = _contains_forbidden_keyword(trimmed)
    if bad_kw:
        return ValidationResult(False, f"Statement contains a disallowed keyword: {bad_kw}.")

    # INTO clause can be used with SELECT to create a table - explicitly block it.
    if re.search(r"\bSELECT\b.*\bINTO\b", trimmed, re.IGNORECASE | re.DOTALL):
        if not re.search(r"\bINTO\s+#?\w+\s+FROM\b", trimmed, re.IGNORECASE):
            pass  # ambiguous phrasing like "SELECT col INTO" alone still needs the guard below
        if re.search(r"\bSELECT\b[^;]*\bINTO\s+\w", trimmed, re.IGNORECASE):
            return ValidationResult(False, "SELECT ... INTO (table creation) is not allowed.")

    return ValidationResult(True, cleaned_sql=trimmed)


def enforce_row_limit(sql: str, max_rows: int = 1000) -> str:
    """
    Best-effort guard so exploratory/AI-generated queries can't return
    unbounded result sets. Only applied when the query has no existing
    TOP / OFFSET-FETCH clause.
    """
    upper = sql.upper()
    if re.search(r"\bTOP\s*\(", upper) or "OFFSET" in upper:
        return sql
    return re.sub(r"^(\s*SELECT\b)", rf"\1 TOP {max_rows}", sql, count=1, flags=re.IGNORECASE)
